const schema={
  Animals:{
    Name: {type:"text",text:"Animal Name:"},
    Habitat_ID: {type:"number",text:"Habitat ID:"},
    Weight: {type:"number",text:"Weight:"},
    Height: {type:"number",text:"Height:"},
    Species: {type:"text",text:"Species:"},
    Animal_ID: {type:"number",text:"Animal ID:"},
    Birth_Date: {type:"date",text:"Birth Date:"},
  },
  Employees:{
    Fname: {type:"number",text:"Employee Name:"},
    Lname: {type:"number",text:"Employee Name:"},
    Employee_ID: {type:"number",text:"Employee ID:"},
    Email: {type:"email",text:"Employee Email:"},
    Start_Date: {type:"date",text:"Employee Start Date:"},
    Birth_Date: {type:"date",text:"Employee Birth Date:"},
    SSN: {type:"number",text:"Employee SSN:"},
    Gender: {type:"enum", text:"Select Gender:", enum:['Male','Female','Other']}
  },
  Animal_Health:{
    Primary_Doctor_ID: {type:"number",text:"Primary Doctor:"},
    Animal_Health_ID: {type:"number",text:"Medical Record ID:"},
    Date_Of_Examination: {type:"date",text:"Date of Examination:"},
    Description: {type:"text",text:"Description:"},
  },
  Zones:{
    Zone_ID: {type:"number",text:"Zone ID:"},
    Name: {type:"text", text:"Name:"},
    Status: {type:"text", text:"Status:"},
    Size: {type:"number", text:"Size:"},
  },
  Habitats:{
    Habitat_ID: {type:"number",text:"Habitat ID:"},
    Zone_ID: {type:"number",text:"Zone ID:"},
    Status: {type:"text",text:"Status:"},
    Date_Opened: {type:"date",text:"Date Opened:"},
    Capacity: {type:"number",text:"Capacity:"},
  },
  Customers:{
    Customer_ID: {type:"number",text:"Customer ID:"},
    Name: {type:"text",text:"Name:"},
    Address: {type:"text",text:"Address:"},
    Phone: {type:"text",text:"Phone:"},
    Email: {type:"text",text:"Email:"},
    user_id: {type:"number",text:"User ID:"},
  },
  Attends_To: {
    Employee_ID: {type:"number",text:"Employee ID:"},
    Animal_ID: {type:"number", text:"Animal ID:"},
    Responsibility: {type:"text", text:"Responsibility:"},
  },
  Items:{
    Item_ID: {type:"number",text:"Item ID:"},
    Shop_ID: {type:"number",text:"Shop ID:"},
    Quantity: {type:"number",text:"Quantity:"},
  },
  Lost_Items:{
    Lost_Item_ID: {type:"number",text:"Lost Item ID:"},
    Customer_ID: {type: "number", text:"Customer ID:"},
    Description: {type: "text",text:"Description:"},
    Status: {type: "text",text:"Status:"},
  },
  Restaurants:{
    Restraunt_ID: {type:"number",text:"Restaurant ID:"},
    Zone_ID: {type: "number", text:"Zone ID:"},
    Name: {type: "text",text:"Name:"},
    Status: {type: "text",text:"Status:"},
  },
  Purchases:{
    Purchase_ID:{type:"number",text:"Purchase ID:"},
    Item_ID:{type:"number",text:"Item ID:"},
    Shop_ID:{type:"number",text:"Shop ID:"},
    Customer_ID:{type:"number",text:"Customer ID:"},
    Quantity:{type:"number",text:"Quantity:"},
    Date:{type:"date",text:"Date:"}
  },
  Timesheets:{
    Employee_Schedule_ID: {type:"number",text:"Schedule ID:"},
    Description: {type: "text", text:"Description:"},
    Employee_ID: {type: "number",text:"Employee ID:"},
    Start_Time: {type:"datetime-local",text: "Start Time:"},
    End_Time: {type:"datetime-local",text:"End Time:"},
  },
  Employee_Schedules:{
    Employee_Schedule_ID: {type:"number",text:"Schedule ID:"},
    Description: {type: "text", text:"Description:"},
    Employee_ID: {type: "number",text:"Employee ID:"},
    Start_Time: {type:"datetime-local",text: "Start Time:"},
    End_Time: {type:"datetime-local",text:"End Time:"},
  },
  Animal_Schedules:{
    Animal_Schedule_ID: {type:"number",text:"Schedule ID:"},
    Description: {type: "text", text:"Description:"},
    Animal_ID: {type: "number",text:"Animal ID:"},
    Start_Time: {type:"datetime-local",text: "Start Time:"},
    End_Time: {type:"datetime-local",text:"End Time:"},
  },
  Shop_Schedules:{
    WaveShaperNode_Schedule_ID: {type:"number",text:"Schedule ID:"},
    Description: {type: "text", text:"Description:"},
    Shop_ID: {type: "number",text:"Shop ID:"},
    Start_Time: {type:"datetime-local",text: "Start Time:"},
    End_Time: {type:"datetime-local",text:"End Time:"},
  },
  Habitat_Schedules:{
    Habitat_Schedule_ID: {type:"number",text:"Schedule ID:"},
    Description: {type: "text", text:"Description:"},
    Habitat_ID: {type: "number",text:"Habitat ID:"},
    Start_Time: {type:"datetime-local",text: "Start Time:"},
    End_Time: {type:"datetime-local",text:"End Time:"},
  },
}

export default schema;